### ISSUE TITLE
@inheritDoc (or @inheritdoc as well) is treated is an invalid PHPDocs tag

### ISSUE THREAD

**Issue by vtos** [moodlehq/moodle-local_moodlecheck#106]
Hi guys, any particular reason `inheritDoc` is considered to be an 'Invalid phpdocs tag'?
Having such tag is really useful and allows to avoid duplicating of PHPDocs for interfaces and their implementation. However, the checker displays the 'Invalid phpdocs tag @inheritDoc used' message for it.

**Comment by stronk7** [comment]
Hi @vtos,

`@inheritdoc` is explicitly forbidden as per our [coding style guidelines](https://moodledev.io/general/development/policies/codingstyle#functions).

Some day we'll complete perform a complete classmap and the tool will be able to know when parent classes have that information documented. Until then, we'll have to live with those warnings.

Note that, if the tool detects that the class has a parent... it only raises a warning about missing docs. Errors are reported if the class has not parent. Just a way to differentiate them.

Ciao :-)
