### ISSUE TITLE
Support union types

### ISSUE THREAD

**Issue by PhMemmel** [moodlehq/moodle-local_moodlecheck#115]
Currently, moodlecheck does not properly detect @param tags in the PHPDoc if a union type is being used in a function.

For example the code
```
/**
 * Some description.
 *
 * @param int|stdClass $idorobject the id of the object or the record as a whole
 */
public static function some_function(int|stdClass $idorobject): void {
  // some code
}
``` 
will throw `Phpdocs for function classname::some_function has incomplete parameters list (error)`.

**Comment by andrewnicols** [comment]
See #113 which should land today.

**Comment by PhMemmel** [comment]
Sorry, only searched issues, not pull requests :see_no_evil:
