### ISSUE TITLE
Fully qualified class names not recognised when using PHP 7.4

### ISSUE THREAD

**Issue by james-cnz** [moodlehq/moodle-local_moodlecheck#116]
The latest version of the checker seems not to handle fully qualified class names in parameter lists when run in an old environment.  I'm using a Moodle package for Windows downloaded from moodle.org .  It uses PHP 7.4 (I assume this is the issue).  The problem doesn't seem to appear in a package using PHP 8.1.

When I check the Moodle Page module, /mod/page, errors include:
 mod/page/classes/analytics/indicator/activity_base.php
 Line 41: Phpdocs for function activity_base::fetch_student_grades has incomplete parameters list (error)

If I change the following line, the error disappears:
 public function fetch_student_grades(\core_analytics\course $course) {
To:
 public function fetch_student_grades(course $course) {

**Comment by andrewnicols** [comment]
Can you provide the file in question as an attachment on this issue?

**Comment by james-cnz** [comment]
OK, I've attached the file I mentioned.  (I've changed the extension to .txt, because GitHub wouldn't let me upload a .php file.)
[activity_base.txt](https://github.com/moodlehq/moodle-local_moodlecheck/files/12206221/activity_base.txt)

**Comment by james-cnz** [comment]
Hi,

The fix seems to work on the example I posted, but not on some other fully qualified class names.  I've noticed it doesn't seem to work when the class is at the root level, e.g. \moodle_page .
I think it needs to stop concatenating if it reaches whitespace.  I think the reason it works on some class names is that it's looping over the array by counting the array size, rather than checking the max key, and the array size changes, causing it to stop before the end of the array.

**Comment by andrewnicols** [comment]
Can you please provide a short code example that's failing?

**Comment by james-cnz** [comment]
Here's one.  Again, renamed from .php to .txt .
[comment.txt](https://github.com/moodlehq/moodle-local_moodlecheck/files/12298535/comment.txt)

**Comment by andrewnicols** [comment]
Hi @james-cnz,

That is passing fine for me. Are you able to provide a simplified example which is definitely failing for you?

**Comment by james-cnz** [comment]
It's failing for me on PHP 7.4.  Here's a minimal file that fails for me.
[test.txt](https://github.com/moodlehq/moodle-local_moodlecheck/files/12300861/test.txt)

**Comment by andrewnicols** [comment]
#119
