### ISSUE TITLE
'/' or '//../' or similar at the end of the path make the report funny

### ISSUE THREAD

**Issue by kordan** [moodlehq/moodle-local_moodlecheck#29]
I used moodlecheck local plugin to test my contrib plugin with:
Path(s) = 'mod/surveypro//../'
and what I got was:
mod/surveypro/classes//../
mod/surveypro/classes//..//adminlib.php
mod/surveypro/classes//..//adminmanageplugins.php
mod/surveypro/classes//..//backup
mod/surveypro/classes//..//backup/moodle2
mod/surveypro/classes//..//backup/moodle2/backup_surveypro_activity_task.class.php
mod/surveypro/classes//..//backup/moodle2/backup_surveypro_settingslib.php
mod/surveypro/classes//..//backup/moodle2/backup_surveypro_stepslib.php
mod/surveypro/classes//..//backup/moodle2/restore_surveypro_activity_task.class.php
mod/surveypro/classes//..//backup/moodle2/restore_surveypro_stepslib.php
mod/surveypro/classes//..//classes
mod/surveypro/classes//..//classes/event
mod/surveypro/classes//..//classes/event/all_items_deleted.php
mod/surveypro/classes//..//classes/event/all_items_hidden.php
mod/surveypro/classes//..//classes/event/all_items_visible.php
mod/surveypro/classes//..//classes/event/all_submissions_deleted.php
mod/surveypro/classes//..//classes/event/all_submissions_exported.php
and much more.

**Comment by kordan** [comment]
worst is that, by adding a trailing '/' to the path, correct @package names are marked as wrong.

**Comment by paulholden** [comment]
This issue is fixed by #43 - the following warning is also repeated when entering "/local/moodlecheck//../" in the _Path(s)_ field currently:

> Warning: Unterminated comment starting line 2 in /${moodledirroot}/local/moodlecheck/file.php on line 144

**Comment by stronk7** [comment]
(closing as fixed by #43 , thanks @paulholden )
