### ISSUE TITLE
@expectedException seen as "Invalid phpdocs tag"

### ISSUE THREAD

**Issue by scara** [moodlehq/moodle-local_moodlecheck#35]
Found when writing a test to check for a given exception: https://github.com/scara/moodle-local_twittercard/blob/6edbdaa695769df22efa496846ab0b3f33bff67d/tests/summarycard_test.php#L295.

**Comment by scara** [comment]
Bumping...

**Comment by stronk7** [comment]
Uhm... was looking to other tags... and I'm seriously thinking that maybe this (#36) is missing some stuff...

The tags also should be @ `recommendedtags` or they will be displayed as not recommended. And, also, if we want to restrict them to testing stuff we'll need to use `pathrestrictedtags`. 100% parallel to the behavior/implementation of `dataProvider` @ #21 

Ciao :-)

**Comment by stronk7** [comment]
Yes!
