### ISSUE TITLE
Invalid phpdocs tag @codingStandardsIgnoreLine used

### ISSUE THREAD

**Issue by markn86** [moodlehq/moodle-local_moodlecheck#38]
I have the following Behat step docs -

```
* @codingStandardsIgnoreLine
* @Given /^I add the element "(?P<element_name>(?:[^"]|\\")*)" to page "(?P<page_number>\d+)" of the "(?P<template_name>(?:[^"]|\\")*)" certificate template$/
```

Moodle check complains about the usage of  '@codingStandardsIgnoreLine'. However, if I remove the '@codingStandardsIgnoreLine' line the local_codechecker complains about the line length. Seems I can't win.

**Comment by mudrd8mz** [comment]
This could be done together with https://tracker.moodle.org/browse/MDLSITE-2824 and pull #18

**Comment by stronk7** [comment]
( done by #41 ) Ciao :-)
