### ISSUE TITLE
Problems with variadic functions

### ISSUE THREAD

**Issue by phager-at** [moodlehq/moodle-local_moodlecheck#42]
Hi,

I couldn't find any syntax being compatible with local_moodlecheck to declare parameters for variadic functions.
Some syntaxes I tried:

```
@param string ...$header desc of parameter
@param string[] $header desc of parameter
@param string $header,... desc of parameter
```

Is there a recommended syntax, or are variadic functions not supported by local_moodlecheck right now?

**Comment by stronk7** [comment]
I think we are missing support for them yet... both in the dockblock and when parsing the parameters. We faced something similar @ #34
