### ISSUE TITLE
Fix or ignore anonymous class returns

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-local_moodlecheck#50]
Code like `return new class extends phpunit_coverage_info` in a coverage.php file is currently generating a _Class extends is not documented_ error.

Perhaps an anonymous class can be skipped modifying the &get_classes function in file.php:
```
if (($this->previous_nonspace_token($tid) == 'new') && ($this->next_nonspace_token($tid) == 'extends')) {
     continue;
}
```

**Comment by scara** [comment]
Hi @ewallah,
would you like to provide a PR including a fixture to the test that the code will fix your issue according to the fixture provided?

TIA,
Matteo

**Comment by stronk7** [comment]
#51 is about this (just created). For reference.
