### ISSUE TITLE
Invalid phpdoc tag for @depends annotation

### ISSUE THREAD

**Issue by sumitnegi933** [moodlehq/moodle-local_moodlecheck#55]
'@depends' tags of PHPUnit is not valid as phpdoc tag. This tag should be treated as valid tag.

Code snippet of test functions.
```
` /**
   * @depends test_add_entry
   */
    public function test_delete_entry() {
        $this->resetAfterTest(true);
        $entryid = $this->create_entry();
        tool_sumitnegi\api::remove($entryid);
        $entry = tool_sumitnegi\api::get($entryid);
        $this->assertEmpty($entry, 'Got data for entryid');
    }`
```

Error on code checking:
![image](https://user-images.githubusercontent.com/1021855/90518159-02f89680-e184-11ea-9d66-9a2ccd38be9b.png)

**Comment by scara** [comment]
For ref purposes, here is where `@depends` is documented: https://phpunit.readthedocs.io/en/7.5/annotations.html#depends .

HTH,
Matteo

**Comment by sumitnegi933** [comment]
Thanks, but I am not cleared what you referring through the document link. 
but I meant that when I use this annotation in my test functions, it is not considered as valid phpdoc tag on code checking process, which should be considered as valid tag.

**Comment by scara** [comment]
Hi @sumitnegi933,
> Thanks, but I am not cleared what you referring through the document link.

I mean: your issue is legit since it's a PHPUnit valid annotation, and the doc is there for reference.

In the past I submitted missing annotations too: in this case I do not know if such a missing is intentional to avoid creating dependencies between tests: let's wait for Moodle HQ thoughts.

HTH,
Matteo

**Comment by stronk7** [comment]
Yeah, the @depends tag is not defined as allowed @ https://docs.moodle.org/dev/Coding_style#Other_specific_tags ... in fact the concept of passing results between tests... does not fit well in my brain.

More yet... we have a good number of "incorrectly" used @depends tags in core already... 

Pity I did read this after merging the PR :-)

**Comment by sumitnegi933** [comment]
Yes I see. I think passing result of one test to other will short your effort to generator prerequisites data which supposed to be present there for test. e.g editing a data needs the data first create, so it might help in the case. before work on this I also checked in core and found it is being used and I thought it may helpful in anyway.
