### ISSUE TITLE
Requires in class files causes error

### ISSUE THREAD

**Issue by bencellis** [moodlehq/moodle-local_moodlecheck#8]
If require statements are made before the class declaration, the checker raises an issue even if the class is the only thing in the file - http://docs.moodle.org/dev/Coding_style#Classes_3.

Ben Ellis
@m00bellis (twitter)

**Comment by stronk7** [comment]
I'm not sure I understand this. Do you mean that global scope code between the file dockblock and the class dockblock are leading to false-positive reports when analysing those dockblocks?
