### ISSUE TITLE
Errors displayed when MoodleCheck encounters a plugin that includes some empty files

### ISSUE THREAD

**Issue by michael-milette** [moodlehq/moodle-local_moodlecheck#86]
When checking plugins that contain some empty files, the following notices and warnings are displayed:

- Notice: Undefined offset: 0 in /local/moodlecheck/rules/phpdocs_basic.php on line 60
- Notice: Undefined offset: 1 in /local/moodlecheck/file.php on line 544
- Notice: Trying to access array offset on value of type null in /local/moodlecheck/file.php on line 544
- Warning: Unterminated comment starting line 2 in /local/moodlecheck/file.php on line 150

These appear to be caused by the fact that there are no tokens if the file is empty.

An example of this might be a plugin under development that includes an empty settings.php file.

Let me know if you have any questions.

Michael Milette

**Comment by stronk7** [comment]
Thanks for the report @michael-milette . Will try to reproduce it locally and find a fix.

**Comment by stronk7** [comment]
Curious, are you files 100% empty (0 bytes)?

I'm trying here with an empty (0 bytes) file and I'm being able to only get these 2:

```
[27-May-2022 18:47:49 Europe/Madrid] PHP Warning:  Undefined array key 0 in local/moodlecheck/rules/phpdocs_basic.php on line 60
[27-May-2022 18:47:49 Europe/Madrid] PHP Warning:  Trying to access array offset on value of type null in local/moodlecheck/rules/phpdocs_basic.php on line 60
```

**Comment by stronk7** [comment]
Ok, I've a patch here that, in early stages, if the file is empty or it doesn't have tokens (a.k.a, PHP code), then skips it with message: `Line 1: The file is empy or doesn't contain PHP code. Skipped.`

As commented above, I've been unable to reproduce some of the reported notices... but I think that with the changes we stop any further processing of empty files before they happen, so it should be enough.

![empty_skipped](https://user-images.githubusercontent.com/167147/170778804-fee3709c-c7b3-446e-990f-3fdf6941b39a.png)

Going to create a pull request with the changes...

**Comment by michael-milette** [comment]
Thanks @stronk7 ,

If the file is skipped, it will likely take care of the other errors. Let me know when the patch is available and I will be happy to test it out.

**Comment by michael-milette** [comment]
Yes, 0 byte files.

**Comment by stronk7** [comment]
You can find the candidate code @ #87

Ciao :-)

**Comment by michael-milette** [comment]
Hi @stronk7 ,

Thank you! Tested it and your patch got rid of the following errors:

- Notice: Undefined offset: 0 in /local/moodlecheck/rules/phpdocs_basic.php on line 60
- Notice: Undefined offset: 1 in /local/moodlecheck/file.php on line 544
- Notice: Trying to access array offset on value of type null in /local/moodlecheck/file.php on line 544

A reminder that you will also need to bump the version number because you modified the language file.

However, I am still getting the following error:

- Warning: Unterminated comment starting line 2 in /local/moodlecheck/file.php on line 162

I am testing about 180 plugins at a time and will try to figure out which one is causing the error.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @stronk7 ,

I have determined that the plugin which is causing nine (9) **Warning: Unterminated comment starting line 2 in /local/moodlecheck/file.php on line 162** messages (one of them is "...starting on line 252") is local/codechecker.

I narrowed down the issue to something under **local/codechecker/phpcs/src/Standards**. If I exclude that path, the messages no longer appear.

Hope this helps.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @stronk7,

Thanks for looking into this more.

Developers should be linting their code and fixing problems before running MoodleCheck on it. However, QA testers just test and and report, not fix the issues. So those folks really appreciate your efforts.

Could you somehow catch the invalid condition and output a generic "File contains one or more invalid comment block" message? As long as it appears in the report within context of the file being tested, it would still be helpful despite its vagueness.

My second choice would be to suppress the warning.

As it is right now, you cannot tell which plugin is generating the warnings if you are are testing in bulk because these messages appear at the top the results, out of context.

If you do nothing, the appearance of the warnings cause confusion and could leave the user to question the completeness of the report. To me, the appearance of an error or warning means that something did not work as designed and is therefore is unreliable. For these reasons, I would rather **doing nothing** not be considered as a solution.

Does that help at all?

Michael

**Comment by stronk7** [comment]
Done, have added [a new commit](https://github.com/moodlehq/moodle-local_moodlecheck/pull/87/commits/9811f6af2b73dffb6d4d89b058c7d2434049cf8c) @ #87, to verify that now there aren't PHP Warnings anymore.

Ciao :-)

**Comment by michael-milette** [comment]
Hi Eloy,

Your latest patch works for me. Thank you!

Michael

**Comment by michael-milette** [comment]
Thank you!

**Comment by michael-milette** [comment]
Hi @stronk7 ,

Reminder: Because you added a string, please update the version number so that it will refresh the cache.

Best regards,

Michael

**Comment by stronk7** [comment]
Whops, thanks for the reminder, I've straight-pushed a commit with the version bump to today (20220602).

Ciao :-)

**Comment by michael-milette** [comment]
Thank you Eloy!
