### ISSUE TITLE
Feature request: Specify plugin in URL

### ISSUE THREAD

**Issue by michael-milette** [moodlehq/moodle-local_moodlecheck#88]
Would it be possible to make it possible to initiate the scan by specifying the plugin in the URL, in a similar way to how moodle-local_codechecker can?

**Comment by stronk7** [comment]
Fun, I had no idea (remembered) that local_codechecker had that feature. Will try to look to it...

**Comment by stronk7** [comment]
Hi @michael-milette,

you may be interested in this PR (see the description). Unless I'm wrong it will enable you to specify paths (or anything else, say exclusions, or rules...) in the URL. 99% copied from the codechecker implementation of the same feature.

Ciao :-)

**Comment by michael-milette** [comment]
Thank you so much @stronk7 !

This is going to be so useful.

Best regards,

Michael

**Comment by stronk7** [comment]
#95 has been merged, so it should be now available via git pull. Let us know if it works as expected, ciao :-)
